iamroot17A: 16주차 스터디
iamroot17/linux pull request #6
Opened 2020-12-14 01:07 UTC by JSYoo5B

* 2020년 12월 12일 (15:00~18:00)    
* 코드 버전: mainline 5.9           
* init/main.c start_kernel() 분석 중
  * local_irq_disable() 분석        
  * boot_cpu_init() 분석            
  * page_address_init() 분석        
  * pr_notice() 분석 (linux_banner) 
* ARM64에서 구현된 atomic operation 관련 내용 분석 
  LL/SC, LSE방식으로 구현된 atomic operation 확인  
  bitops에서 구현된 CAS(Compare-And-Swap) 방식 확인

2020-12-14 04:11 UTC, JSYoo5B commented
잘못된 부분이 있나 확인 부탁드립니다.

별 문제 없으면 며칠 뒤 알아서 merge 해 놓도록 하겠습니다.

2020-12-14 16:00 UTC, dngthe93 requested changes, later dismissed
정리 감사합니다.  
나름대로 수정할 사항 리뷰해보았습니다.

(리뷰에 있는 Request changes 기능이 궁금하여 체크해보았습니다.)

2020-12-14 16:00 UTC, dngthe93 commented on arch/arm64/include/asm/smp.h
> + *; raw_cpu_ptr의 macro에서 나온 주소 값을 pointer indirect 연산을 통해
> pointer indirect 연산을 통해

라는 문장 보다는,
> pointer dereference operator를 통해

라는 표현을 쓰는게 어떨까요?

2020-12-14 16:00 UTC, dngthe93 commented on include/linux/cpumask.h
> + *; (NR_CPUS의 갯수만큼 bit를 표현하기 위한 unsigned long 배열)
`갯수` 보다는 `개수`가 더 적절할 것 같습니다

2020-12-14 16:00 UTC, dngthe93 commented on include/linux/types.h
> + *; BITS_TO_LONGS는 해당 bit를 표현하기 위해 필요한 unsigned long의 갯수를
`갯수` 보다는 `개수`가 더 적절할 것 같습니다

2020-12-14 16:00 UTC, dngthe93 commented on kernel/cpu.c
> +		 *; set_cpu_online()은 __num_online_cpus의 갯수 조절을 위해
`갯수` 보다는 `개수`가 더 적절할 것 같습니다

2020-12-14 16:00 UTC, dngthe93 commented on arch/arm64/include/asm/lse.h
> + *; 현재 빌드 config 설정에 따라 LSE방식 혹은 LL/SC방식을 선택하게 된다.
> LSE방식 혹은 LL/SC방식을 선택하게 된다.

보다는

> (LSE or LL/SC) 방식 혹은 (LL/SC) 방식을 선택하게 된다.

가 좀 더 명확하게 이해가 잘 될 것 같습니다.

2020-12-14 16:04 UTC, dngthe93 commented on mm/highmem.c
> +	 *; 그런데 왜 여기에서는 hlist가 아니라 list를 사용하는지 의문
`page_address_htable` 자료구조는 tail에다가 추가하는 기능이 필요했나봅니다.  
정말 그러한지는 나중에 분석해보면 좋을 것 같은데... 이후 진도에서 나올지 궁금하네요.

2020-12-15 00:12 UTC, JSYoo5B commented on arch/arm64/include/asm/smp.h
> + *; raw_cpu_ptr의 macro에서 나온 주소 값을 pointer indirect 연산을 통해
pointer dereference operator라는 명칭이 있었군요.

생각나는 단어가 indirect 연산이었습니다.

2020-12-15 00:12 UTC, JSYoo5B commented on arch/arm64/include/asm/lse.h
> + *; 현재 빌드 config 설정에 따라 LSE방식 혹은 LL/SC방식을 선택하게 된다.
정리하다가 내용 생략이 좀 많이 되었네요.
말씀하신게 좀 더 명확할 것 같습니다.

2020-12-15 00:18 UTC, JSYoo5B commented on mm/highmem.c
> +	 *; 그런데 왜 여기에서는 hlist가 아니라 list를 사용하는지 의문
저희가 분석할때도 흐름상 원래 아무 일도 안 하는 부분이었기때문에 과연 나타날지 의문이네요.

해당 부분에 대하여 blame으로 확인해 보니 제일 첫 commit이 나오는군요.
더 이전 기록이라서 정확한 원인은 알 수 없네요.

혹시나 hlist가 이후 개발되어 아직 수정되지 않은 것인가 의심해봤는데
hlist도 최초 commit에서 나타나서 알 수가 없네요.

tail에서 추가하는 기능이 없다면 refactoring으로 기여를 할 수도 있어 보입니다.

2020-12-15 00:19 UTC, JSYoo5B commented on include/linux/cpumask.h
> + *; (NR_CPUS의 갯수만큼 bit를 표현하기 위한 unsigned long 배열)
개수가 표준어였군요. 아래 리뷰 부분도 같이 수정해 놓도록 하겠습니다.

2020-12-15 00:22 UTC, JSYoo5B commented on kernel/cpu.c
> +		 *; set_cpu_online()은 __num_online_cpus의 갯수 조절을 위해
여기는 개수보단 값 이란 표현이 더 명학해보이네요.

2020-12-15 00:34 UTC, JSYoo5B commented
기존 commit에 존재하던 맞춤법 문제도 같이 수정합니다.

2020-12-17 03:17 UTC, merged